name: hairsalon_prokit
description: A new Flutter project.
version: 2.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Base
  cupertino_icons: ^1.0.5
  nb_utils: ^5.0.8-beta.2
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^5.0.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  #Hair Salon
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: 4.0.1
  dots_indicator: ^3.0.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.5

  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true
  assets:
     - images/

